#!/usr/bin/env bash
################################################################
# copy this script to /etc/snmp/ and make it executable:       #
# chmod +x /etc/snmp/asterisk                                  #
# ------------------------------------------------------------ #
# edit your snmpd.conf and include:                            #
# extend asterisk /etc/snmp/asterisk                           #
# ------------------------------------------------------------ #
# restart snmpd and activate the app for desired host          #
# ------------------------------------------------------------ #
# please make sure you have the path/binaries below            #
################################################################
ASCLI='/usr/bin/env asterisk'

if [ -f $ASCLI ];
then
    $ASCLI -rx "core show uptime" > /dev/null
    if [ $? -ne 0 ]; then
        # Asterisk not running, silently exit.
        exit 0
    fi

    echo "<<<asterisk>>>"
    $ASCLI -rx "core show channels" | awk '/active calls/ { print "Calls=" $1 } /active channels/ { print "Channels=" $1}'
    $ASCLI -rx 'sip show peers' | awk '/sip peers/ { print "SipPeers=" $1 "\nSipMonOnline=" $5 "\nSipMonOffline=" $7 "\nSipUnMonOnline=" $10 "\nSipUnMonOffline=" $12}'

else
   exit 0
fi
