#!/usr/bin/env perl
#Copyright (c) 2026, Zane C. Bowers-Hadley
#All rights reserved.
#
#Redistribution and use in source and binary forms, with or without modification,
#are permitted provided that the following conditions are met:
#
#   * Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#   * Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
#THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
#ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
#WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
#IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
#INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
#BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
#LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
#THE POSSIBILITY OF SUCH DAMAGE.

=head1 NAME

borgbackup - LibreNMS JSON SNMP extend for gathering backups for borg

=head1 VERSION

0.1.0

=head1 SYNOPSIS

borgbackup [-c <config>] [-o <output dir>] [-u] [-p] [-Z] [-v] [-V] [-h]

=head1 DESCRIPTION

This uses 'borg info $repo --json' to fetch info on the specified borg repos
and write the info out to files.

The information is then writen out two two files under the output directory.

    - extend_return :: This file contains the data for the extend in
        gzip+base64 compressed format if applicable.

    - pretty :: Pretty printed and sorted JSON.

This is done for three reasons. The first is SNMPD and the users with read perms
for the repos are likely to be different. The second is lock time out, even with
1 second, means the command likely won't complete in a timely manner for larger
repos.

For SNMPD generally going to be setup like this.

    extend borgbackup /bin/cat /var/cache/borgbackup_extend

Then the extend is set to be ran via cron.

    */5 * * * * /etc/snmp/extends/borgbackup -u -Z

=head1 USAGE

When called without flags, it reads from the cache file if it exists.
Use -u to update the cache, or -u -v for verbose updates.

    /etc/snmp/extends/borgbackup -u -v

=head1 FLAGS

=head2 -c <config file>

The config file to use for the extend.

Default :: /usr/local/etc/borgbackup_extend.ini

=head2 -o <output dir>

The output directory write the pretty JSON file to and the file to use
for the SNMP extend.

Default :: /var/cache/borgbackup_extend

=head2 -u

Update mode. When called from snmpd, it reads from the cache file instead
of running borg commands directly.

=head2 -p

Pretty print the JSON output.

=head2 -Z

GZip+Base64 compress the results.

=head2 -v

Verbose output. Print status info to STDERR.

=head2 -V

Print version and exit.

=head2 -h

Print help info.

=head1 CONFIG

The config file is a ini file and handled by L<Coonfig::Tiny>.

    - mode :: single or multi, for if this is a single repo or for
            multiple repos.
        - Default :: single

    - repo :: Directory for the borg backup repo.
        - Default :: undef

    - passphrase :: Passphrase for the borg backup repo.
        - Default :: undef

    - passcommand :: Passcommand for the borg backup repo.
        - Default :: undef

For single repos all those variables are in the root section of the config,
so lets the repo is at '/backup/borg' with a passphrase of '1234abc'.

    repo=/backup/borg
    repo=1234abc

For multi, each section outside of the root represents a repo. So if there is
'/backup/borg1' with a passphrase of 'foobar' and '/backup/derp' with a passcommand
of 'pass show backup' it would be like below.

    mode=multi

    [borg1]
    repo=/backup/borg1
    passphrase=foobar

    [derp]
    repo=/backup/derp
    passcommand=pass show backup

If 'passphrase' and 'passcommand' are both specified, then passcommand is used.

=head1 JSON RETURN

The return is a LibreNMS JSON style SNMP extend as defined at
L<https://docs.librenms.org/Developing/Application-Notes/#librenms-json-snmp-extends>

The following key info is relevant to the .data .

    - .mode :: The mode it was ran in, either single or multi.

Totaled info is in the hash .totals.

    - .totals.errored :: Total number of repos that info could not be fetched for.
        - Type :: repos

    - .totals.locked :: Total number of locked repos
        - Type :: repos

    - .totals.locked_for :: Longest time any repo has been locked.
        - Type :: seconds

    - .totals.time_since_last_modified :: Largest time - mtime for the repo directory
        - Type :: seconds

    - .total.total_chunks :: Total number of checks between all repos.
        - Type :: chunks

    - .total.total_csize :: Total compressed size of all archives in all repos.
        - Type :: bytes

    - .total.total_size :: Total uncompressed size of all archives in all repos.
        - Type :: bytes

    - .total.total_unique_chunks :: Total number of unique chuckes in all repos.
        - Type :: chunks

    - .total.unique_csize :: Total deduplicated size of all archives in all repos.
        - Type :: bytes

    - .total.unique_size :: Total number of chunks in all repos.
        - Type :: chunks

Each repo then has it's own hash under .repo .

    - .repo.$repo.error :: If defined, this is the error encounted when
            attempting to get repo info.
        - Type :: string

    - .repo.$repo.locked_for :: How long the repo has been locked for if
            locked. If it is not locked this is undef.
        - Type :: seconds

    - .repo.$repo.time_since_last_modified :: time - mtime for the repo directory
        - Type :: seconds

    - .repo.$repo.total_chunks :: Total number of checks for the repo.
        - Type :: chunks

    - .repo.$repo.total_csize :: Total compressed size of all archives for the repo.
        - Type :: bytes

    - .repo.$repo.total_size :: Total uncompressed size of all archives the repo.
        - Type :: bytes

    - .repo.$repo.total_unique_chunks :: Total number of unique chuckes the repo.
        - Type :: chunks

    - .repo.$repo.unique_csize :: Total deduplicated size of all archives the repo.
        - Type :: bytes

    - .repo.$repo.unique_size :: Total number of chunks in the repo.
        - Type :: chunks

=cut

use strict;
use warnings;
use Config::Tiny;
use JSON;
use Getopt::Long qw( GetOptions :config no_ignore_case );
use File::Slurp;
use File::Path qw(make_path);
use MIME::Base64;
use IO::Compress::Gzip qw(gzip $GzipError);
use String::ShellQuote;
use Pod::Usage;

our $output_dir = '/var/cache/borgbackup_extend';
my $config_file = '/usr/local/etc/borgbackup_extend.ini';
my $verbose = 0;
my $pretty = 0;
my $compress = 0;
my $update = 0;

sub VERSION_MESSAGE {
	print "borgbackup SNMP extend 0.1.0\n";
}

sub HELP_MESSAGE {
	print "borgbackup SNMP extend 0.1.0\n\n";
	print "Usage: borgbackup [options]\n\n";
	print "Options:\n";
	print "  -c <file>   Config file (default: $config_file)\n";
	print "  -o <dir>    Output directory (default: $output_dir)\n";
	print "  -u          Update mode - regenerate cache from borg repos\n";
	print "  -p          Pretty print JSON output\n";
	print "  -Z          GZip+Base64 compress the cache file\n";
	print "  -v          Verbose output to STDERR\n";
	print "  -V          Print version and exit\n";
	print "  -h          Print this help message\n";
	print "\n";
	print "When called without -u, reads from cache file for SNMP extend.\n";
	print "\n";
	print "Typical usage:\n";
	print "  SNMPD:  extend borgbackup /bin/cat /var/cache/borgbackup_extend/extend_return\n";
	print "  Cron:   */5 * * * * /usr/local/lib/snmpd/borgbackup -u -Z\n";
	print "\n";
	print "Config file (INI format):\n";
	print "  mode=multi                    # single or multi\n";
	print "  repo=/path/to/repo            # for single mode\n";
	print "  passphrase=secret              # or use passcommand\n";
	print "\n";
	print "  [repo1]                       # for multi mode\n";
	print "  repo=/path/to/repo1\n";
	print "  passphrase=secret1\n";
	print "\n";
	print "  [repo2]\n";
	print "  repo=/path/to/repo2\n";
	print "  passcommand=pass show repo2\n";
}

GetOptions(
	'c=s'   => \$config_file,
	'o=s'   => \$output_dir,
	'v'     => \$verbose,
	'p'     => \$pretty,
	'Z'     => \$compress,
	'u'     => \$update,
	'V'     => sub { VERSION_MESSAGE(); exit 0; },
	'h'     => sub { HELP_MESSAGE(); exit 0; },
) or die "Error in command line arguments\n";
if ($verbose) {
	warn "DEBUG: verbose=$verbose, update=$update, pretty=$pretty, compress=$compress\n";
}

sub finish {
	my (%opts) = @_;

	if ( !-e $output_dir ) {
		make_path($output_dir) or die( 'could not create the output dir, "' . $output_dir . '",' );
	} elsif ( -e $output_dir && !-d $output_dir ) {
		die( '"' . $output_dir . '" exists, but is not a directory' );
	}

	my $j = JSON->new;
	if ($pretty) {
		$j->pretty(1);
		$j->canonical(1);
	}

	my $return_string = $j->encode( $opts{to_return} );

	if ($compress) {
		my $compressed_string;
		gzip \$return_string => \$compressed_string;
		my $compressed = encode_base64($compressed_string);
		$compressed =~ s/\n//g;
		$compressed = $compressed . "\n";
		if ( length($compressed) > length($return_string) ) {
			if ($verbose) {
				print STDERR "Writing uncompressed extend_return to: $output_dir/extend_return\n";
			}
			write_file( $output_dir . '/extend_return', $return_string );
		} else {
			if ($verbose) {
				print STDERR "Writing compressed extend_return to: $output_dir/extend_return\n";
			}
			write_file( $output_dir . '/extend_return', $compressed );
		}
	} else {
		if ($verbose) {
			print STDERR "Writing extend_return to: $output_dir/extend_return\n";
		}
		write_file( $output_dir . '/extend_return', $return_string );
	}

	if ($verbose) {
		print STDERR "Writing pretty JSON to: $output_dir/pretty\n";
	}
	write_file( $output_dir . '/pretty', $return_string );

	exit $opts{to_return}->{error};
} ## end sub finish

my $to_return = {
	data => {
		mode   => 'single',
		totals => {
			total_chunks             => 0,
			total_csize              => 0,
			total_size               => 0,
			total_unique_chunks      => 0,
			unique_csize             => 0,
			unique_size              => 0,
			locked                   => 0,
			time_since_last_modified => undef,
			errored                  => 0,
			locked_for               => undef,
		},
		repos => {},
	},
	version     => 1,
	error       => 0,
	errorString => '',
};

if ( !$update && !$pretty ) {
	my $cache_extra = '';
	if ($compress) {
		$cache_extra = '.snmp';
	}
	if ( -f $output_dir . '/extend_return' . $cache_extra ) {
		my $old = read_file( $output_dir . '/extend_return' . $cache_extra );
		print $old;
		exit 0;
	} else {
		$update = 1;
	}
}

if ($verbose) {
	print STDERR "Processing repos in mode: update\n";
}

# attempt to read in the config
my $config;
eval {
	my $raw_config = read_file($config_file);
	($config) = Config::Tiny->read_string($raw_config);
};
if ($@) {
	$to_return->{error}       = 1;
	$to_return->{errorString} = 'Failed reading config file "' . $config_file . '"... ' . $@;
	finish( to_return => $to_return );
}

if ($verbose) {
	print STDERR "Config file: $config_file\n";
}

if ( !defined( $config->{_}{mode} ) ) {
	$config->{_}{mode} = 'single';
	if ($verbose) {
		print STDERR "Config: mode not set, defaulting to 'single'\n";
	}
} elsif ( $config->{_}{mode} ne 'single' && $config->{_}{mode} ne 'multi' ) {
	$to_return->{error}       = 2;
	$to_return->{errorString} = '"' . $config->{_}{mode} . '" mode is not set to single or multi';
	finish( to_return => $to_return );
}

$to_return->{data}{mode} = $config->{_}{mode};
if ($verbose) {
	print STDERR "Config: mode set to '" . $config->{_}{mode} . "'\n";
}

# get a list of repos to use
my @repos;
if ( $config->{_}{mode} eq 'single' ) {
	# if single, just create a single repo
	push( @repos, 'single' );
	$config->{single} = {};
	if ($verbose) {
		print STDERR "Config: single mode, using root section config\n";
	}

	# make sure we have passcommand or passphrase with passphrase being used as the default
	if ( !defined( $config->{_}{passcommand} ) && !defined( $config->{_}{passphrase} ) ) {
		$to_return->{error}       = 3;
		$to_return->{errorString} = 'Neither passcommand or passphrase defined';
		finish( to_return => $to_return );
	} elsif ( $config->{_}{passphrase} ) {
		$config->{single}{passphrase} = $config->{_}{passphrase};
		if ($verbose) {
			print STDERR "Config: using passphrase from root section\n";
		}
	} elsif ( $config->{_}{passcommand} ) {
		$config->{single}{passcommand} = $config->{_}{passcommand};
		if ($verbose) {
			print STDERR "Config: using passcommand from root section\n";
		}
	}

	# make sure have a repo specified
	if ( !defined( $config->{_}{repo} ) ) {
		$to_return->{error}       = 4;
		$to_return->{errorString} = 'repo is not defined';
		finish( to_return => $to_return );
	}
	$config->{single}{repo} = $config->{_}{repo};
	if ($verbose) {
		print STDERR "Config: repo path: " . $config->{_}{repo} . "\n";
	}

} else {
	# we don't want _ as that is the root of the ini file
	@repos = grep( !/^\_$/, keys( %{$config} ) );
	if ($verbose) {
		print STDERR "Config: multi mode, found " . scalar(@repos) . " repos: " . join(', ', @repos) . "\n";
	}
}

my @totals
	= ( 'total_chunks', 'total_csize', 'total_size', 'total_unique_chunks', 'unique_csize', 'unique_size', 'locked' );
my @stats = ( 'total_chunks', 'total_csize', 'total_size', 'total_unique_chunks', 'unique_csize', 'unique_size' );

print "Processing " . scalar(@repos) . " repos...\n";

foreach my $repo (@repos) {
	print "Processing repo $repo\n";
	if ($verbose) {
		print STDERR "Processing repo: $repo\n";
	}

	my $process = 1;

	# unset borg pass bits
	delete( $ENV{BORG_PASSPHRASE} );
	delete( $ENV{BORG_PASSCOMMAND} );

	my $repo_info = {
		total_chunks             => 0,
		total_csize              => 0,
		total_size               => 0,
		total_unique_chunks      => 0,
		unique_csize             => 0,
		unique_size              => 0,
		locked                   => 0,
		time_since_last_modified => undef,
		error                    => undef,
		locked_for               => undef,
	};

	if ( !defined( $config->{$repo}{passcommand} ) && !defined( $config->{$repo}{passphrase} ) ) {
		$to_return->{error} = 3;
		$to_return->{errorString}
			= $to_return->{errorString} . "\n" . 'Neither passcommand or passphrase defined for ' . $repo;
		$process = 0;
		if ($verbose) {
			print STDERR "  ERROR: No passphrase or passcommand for $repo\n";
		}
	}

	if ( !defined( $config->{$repo}{repo} ) ) {
		$to_return->{error}       = 4;
		$to_return->{errorString} = $to_return->{errorString} . "\n" . 'repo is not defined for ' . $repo;
		$process                  = 0;
		if ($verbose) {
			print STDERR "  ERROR: No repo path defined for $repo\n";
		}
	}

	if ($process) {
		if ($verbose) {
			print STDERR "  Repo path: " . $config->{$repo}{repo} . "\n";
		}

		my $nonce_file = $config->{$repo}{repo} . '/nonce';
		my $mtime;
		if ( -e $nonce_file ) {
			if ($verbose) {
				print STDERR "  Checking nonce file mtime: $nonce_file\n";
			}
			( undef, undef, undef, undef, undef, undef, undef, undef, undef, $mtime, undef, undef, undef ) = stat($nonce_file);
		} else {
			if ($verbose) {
				print STDERR "  No nonce file found, using repo directory mtime: " . $config->{$repo}{repo} . "\n";
			}
			( undef, undef, undef, undef, undef, undef, undef, undef, undef, $mtime, undef, undef, undef ) = stat( $config->{$repo}{repo} );
		}

		my $time_diff = time - $mtime;
		$repo_info->{time_since_last_modified} = $time_diff;
		if ($verbose) {
			print STDERR "  Time since last modified: $time_diff seconds\n";
		}

		# if we don't have a largest time diff or if it is larger than then
		# the old one save the time diff
		if ( !defined( $to_return->{data}{totals}{time_since_last_modified} )
			|| $to_return->{data}{totals}{time_since_last_modified} < $time_diff )
		{
			$to_return->{data}{totals}{time_since_last_modified} = $time_diff;
		}

		if ( defined( $config->{$repo}{passcommand} ) ) {
			$ENV{BORG_PASSCOMMAND} = $config->{$repo}{passcommand};
		} else {
			$ENV{BORG_PASSPHRASE} = $config->{$repo}{passphrase};
		}

		my $command    = 'borg info ' . shell_quote( $config->{$repo}{repo} ) . ' --json 2>&1';
		if ($verbose) {
			print STDERR "  Command: $command\n";
		}
		my $output_raw = `$command`;

		my $info;
		eval { $info = decode_json($output_raw); };
		if ($@) {
			my $error = $@;
			if ( $output_raw =~ /lock.*lock\.exclusive/ ) {
				$repo_info->{locked} = 1;

				my $lock_file = $config->{$repo}{repo} . '/lock.exclusive';
				if ($verbose) {
					print STDERR "  Repo is locked, checking: $lock_file\n";
				}
				my ( $lock_dev, $lock_ino, $lock_mode, $lock_nlink, $lock_uid, $lock_gid, $lock_rdev, $lock_size, $lock_atime, $lock_mtime, $lock_ctime, $lock_blksize, $lock_blocks ) = stat($lock_file);
				$repo_info->{locked_for} = time - $lock_ctime;
				if ($verbose) {
					print STDERR "  Repo is locked for " . $repo_info->{locked_for} . " seconds\n";
				}
			} else {
				$repo_info->{error} = $error;
				if ($verbose) {
					print STDERR "  ERROR: " . $error . "\n";
				}
			}
		} else {
			if ( defined( $info->{cache} ) && defined( $info->{cache}{stats} ) ) {
				for my $stat (@stats) {
					$repo_info->{$stat} = $info->{cache}{stats}{$stat};
				}
				if ($verbose) {
					print STDERR "  Stats: total_size=" . $repo_info->{total_size} . ", total_csize=" . $repo_info->{total_csize} . "\n";
				}
			}
		}

		for my $total (@totals) {
			$to_return->{data}{totals}{$total} = $to_return->{data}{totals}{$total} + $repo_info->{$total};
		}

		if ( defined( $repo_info->{error} ) ) {
			$to_return->{data}{totals}{errored}++;
		}

		if ( !defined( $to_return->{data}{totals}{locked_for} )
			|| $to_return->{data}{totals}{locked_for} < $repo_info->{locked_for} )
		{
			$to_return->{data}{totals}{locked_for} = $repo_info->{locked_for};
		}
	} ## end if ($process)

	$to_return->{data}{repos}{$repo} = $repo_info;
} ## end foreach my $repo (@repos)

if ($verbose) {
	print STDERR "Totals:\n";
	print STDERR "  errored: " . $to_return->{data}{totals}{errored} . "\n";
	print STDERR "  locked: " . $to_return->{data}{totals}{locked} . "\n";
	print STDERR "  total_size: " . $to_return->{data}{totals}{total_size} . "\n";
	print STDERR "  total_csize: " . $to_return->{data}{totals}{total_csize} . "\n";
}

finish( to_return => $to_return );
