#!/usr/local/bin/perl

# Add this to snmpd.conf as below.
# extend fbsdnfsclient /etc/snmp/fbsdnfsclient

my $nfsstatOutput=`/usr/bin/nfsstat`;
my @nfsstatOutputA=split( /\n/, $nfsstatOutput );
my $int=0;

my (
	$Getattr,
	$Setattr,   
	$Lookup,
	$Readlink,
	$Read,
	$Write,
    $Create,
    $Remove,
	$Rename,
	$Link,
	$Symlink,
	$Mkdir,
	$Rmdir,
	$Readdir,
	$RdirPlus,
    $Access,
	$Mknod,
    $Fsstat,
    $Fsinfo,
	$PathConf,
    $Commit,
	$TimedOut,
	$Invalid,
	$XReplies,
	$Retries,
	$Requests,
	$AttrHits,
    $AttrMisses,
	$LkupHits,
    $LkupMisses,
	$BioRHits,
	$BioRMisses,
	$BioWHits,
    $BioWMisses,
	$BioRLHits,
	$BioRLMisses,
	$BioDHits,
	$BioDMisses,
	$DirEHits,
    $DirEMisses,
	$AccsHits,
    $AccsMisses,
	);

while( defined( $nfsstatOutputA[$int] ) ){
	$nfsstatOutputA[$int]=~s/^ +//;
	$nfsstatOutputA[$int]=~s/ +/ /g;

	if ( $int == 3 ){
		(
		 $Getattr,
		 $Setattr,   
		 $Lookup,
		 $Readlink,
		 $Read,
		 $Write,
		 $Create,
		 $Remove,
		)=split( /\ /, $nfsstatOutputA[$int] );
	
	}

	if ( $int == 5 ){
		(
		 $Rename,
		 $Link,
		 $Symlink,
		 $Mkdir,
		 $Rmdir,
		 $Readdir,
		 $RdirPlus,
		 $Access,
		)=split( /\ /, $nfsstatOutputA[$int] );
	
	}

	if ( $int == 7 ){
		(
		 $Mknod,
		 $Fsstat,
		 $Fsinfo,
		 $PathConf,
		 $Commit,
		)=split( /\ /, $nfsstatOutputA[$int] );
	
	}

	if ( $int == 10 ){
		(
		 $TimedOut,
		 $Invalid,
		 $XReplies,
		 $Retries,
		 $Requests,
		)=split( /\ /, $nfsstatOutputA[$int] );
	
	}

	if ( $int == 13 ){
		(
		 $AttrHits,
		 $AttrMisses,
		 $LkupHits,
		 $LkupMisses,
		 $BioRHits,
		 $BioRMisses,
		 $BioWHits,
		 $BioWMisses,
		)=split( /\ /, $nfsstatOutputA[$int] );
	
	}

	if ( $int == 15 ){
		(
		 $BioRLHits,
		 $BioRLMisses,
		 $BioDHits,
		 $BioDMisses,
		 $DirEHits,
		 $DirEMisses,
		 $AccsHits,
		 $AccsMisses,
		)=split( /\ /, $nfsstatOutputA[$int] );
	
	}
	
	$int++;
}

print $Getattr."\n".
	$Setattr."\n".
	$Lookup."\n".
	$Readlink."\n".
	$Read."\n".
	$Write."\n".
    $Create."\n".
    $Remove."\n".
	$Rename."\n".
	$Link."\n".
	$Symlink."\n".
	$Mkdir."\n".
	$Rmdir."\n".
	$Readdir."\n".
	$RdirPlus."\n".
    $Access."\n".
	$Mknod."\n".
    $Fsstat."\n".
    $Fsinfo."\n".
	$PathConf."\n".
    $Commit."\n".
	$TimedOut."\n".
	$Invalid."\n".
	$XReplies."\n".
	$Retries."\n".
	$Requests."\n".
	$AttrHits."\n".
    $AttrMisses."\n".
	$LkupHits."\n".
    $LkupMisses."\n".
	$BioRHits."\n".
	$BioRMisses."\n".
	$BioWHits."\n".
    $BioWMisses."\n".
	$BioRLHits."\n".
	$BioRLMisses."\n".
	$BioDHits."\n".
	$BioDMisses."\n".
	$DirEHits."\n".
    $DirEMisses."\n".
	$AccsHits."\n".
    $AccsMisses."\n";
