#!/usr/local/bin/perl

# Add this to snmpd.conf as below.
# extend fbsdnfsserver /etc/snmp/fbsdnfsserver

use strict;
use warnings;
use JSON;
use Getopt::Std;

#gets the options
my %opts=();
getopts('p', \%opts);

my $nfsstatOutput=`/usr/bin/nfsstat`;
my @nfsstatOutputA=split( /\n/, $nfsstatOutput );
my $VERSION=1;
my $int=0;

my %tojson;
$tojson{'version'}=$VERSION;
$tojson{'error'}='0';
$tojson{'errorString'}='';
$tojson{'data'}={};

while( defined( $nfsstatOutputA[$int] ) ){
	$nfsstatOutputA[$int]=~s/^ +//;
	$nfsstatOutputA[$int]=~s/ +/ /g;

	if ( $int == 19 ){
		(
		 $tojson{'data'}{'Getattr'},
		 $tojson{'data'}{'Setattr'},
		 $tojson{'data'}{'Lookup'},
		 $tojson{'data'}{'Readlink'},
		 $tojson{'data'}{'Read'},
		 $tojson{'data'}{'Write'},
		 $tojson{'data'}{'Create'},
		 $tojson{'data'}{'Remove'},
		)=split( /\ /, $nfsstatOutputA[$int] );
	
	}

	if ( $int == 21 ){
		(
		 $tojson{'data'}{'Rename'},
		 $tojson{'data'}{'Link'},
		 $tojson{'data'}{'Symlink'},
		 $tojson{'data'}{'Mkdir'},
		 $tojson{'data'}{'Rmdir'},
		 $tojson{'data'}{'Readdir'},
		 $tojson{'data'}{'RdirPlus'},
		 $tojson{'data'}{'Access'}
		)=split( /\ /, $nfsstatOutputA[$int] );
	
	}

	if ( $int == 23 ){
		(
		 $tojson{'data'}{'Mknod'},
		 $tojson{'data'}{'Fsstat'},
		 $tojson{'data'}{'Fsinfo'},
		 $tojson{'data'}{'PathConf'},
		 $tojson{'data'}{'Commit'}
		)=split( /\ /, $nfsstatOutputA[$int] );
	
	}

	if ( $int == 25 ){
		(
		 $tojson{'data'}{'RetFailed'}
		)=split( /\ /, $nfsstatOutputA[$int] );
	
	}

	if ( $int == 27 ){
		(
		 $tojson{'data'}{'Faults'}
		)=split( /\ /, $nfsstatOutputA[$int] );
	
	}

	if ( $int == 30 ){
		(
		 $tojson{'data'}{'Inprog'},
		 $tojson{'data'}{'Idem'},
		 $tojson{'data'}{'Nonidem'},
		 $tojson{'data'}{'Misses'}
		)=split( /\ /, $nfsstatOutputA[$int] );
	
	}

	if ( $int == 33 ){
		(
		 $tojson{'data'}{'WriteOps'},
		 $tojson{'data'}{'WriteRPC'},
		 $tojson{'data'}{'Opsaved'}
		)=split( /\ /, $nfsstatOutputA[$int] );
		
	}
	
	$int++;
}

my $j=JSON->new;

if ( $opts{p} ){
        $j->pretty(1);
}

print $j->encode( \%tojson );

if ( $opts{p} ){
	$j->pretty(1);
}
