#!/usr/bin/env bash
# MDADM SNMP extension for LibreNMS
# Outputs a list of devices
list_devices() {
    for device in "${1}/slaves/"*; do
        if [ "${2,,}" == 'count' ]; then
            ((devCount++))
        elif [ "${2,,}" != 'missing' ] || [ ! -e "${device}" ]; then
            printf "%b\t    \"$(basename "${device}")\"" "${multiDisk}"
            multiDisk=',\n'
        fi
    done
    [ "${devCount}" ] && echo "${devCount}"
}

# Outputs either 0, 100, or the value of the file referenced
maybe_get() {
    if [ -f "${1}" ] && [ "$(cat "${1}")" != 'none' ]; then
        cat "${1}"
    else
        echo 0
    fi
}

mdadmSNMPOutput='{ "data": ['
for mdadmArray in "/dev/md"[[:digit:]]*; do
    # Ignore partitions
    if [[ "${mdadmArray}" =~ '/dev/md'[[:digit:]]+'p' ]]; then continue; fi

    mdadmName="$(basename "$(realpath "${mdadmArray}")")"
    mdadmSysDev="/sys/block/${mdadmName}"

    read -r -d '' mdadmOutput <<MDADMJSON
    ${multiArray}{
        "name": "${mdadmName}",
        "level": "$(cat "${mdadmSysDev}/md/level")",
        "size": "$((($(cat "${mdadmSysDev}/size") * 1024) / 2))",
        "disc_count": "$(cat "${mdadmSysDev}/md/raid_disks")",
        "hotspare_count": "$((($(list_devices "${mdadmSysDev}" count "${mdadmSysDev}") - $(cat "${mdadmSysDev}/md/raid_disks"))))",
        "device_list": [
$(list_devices "${mdadmSysDev}")
        ],
        "missing_devices_list": [
$(list_devices "${mdadmSysDev}" missing)
        ],
        "state": "$(cat "${mdadmSysDev}/md/array_state")",
        "action": "$(maybe_get "${mdadmSysDev}/md/sync_action")",
        "degraded": "$(maybe_get "${mdadmSysDev}/md/degraded")",
        "sync_speed": "$(($(maybe_get "${mdadmSysDev}/md/sync_speed") * 1024))",
        "sync_completed": "$(maybe_get "${mdadmSysDev}/md/sync_completed")"
    }
MDADMJSON
    # Add a comma only after the first item
    multiArray=','
    mdadmSNMPOutput+="${mdadmOutput}"
done

    read -r -d '' metadataOutput <<METADATA
],
    "error": "0",
    "errorString": null,
    "version": "1"
}
METADATA

 sed 's/\s//g' <<< "${mdadmSNMPOutput//$'\n'/}${metadataOutput//$'\n'/}"

# Very basic debug flag
[ "${1,,}" == '--debug' ] && echo "${mdadmSNMPOutput}${metadataOutput}"
