#!/bin/sh
# Please make sure the paths below are correct.
# Alternatively you can put them in $0.conf, meaning if you've named
# this script ntp-client then it must go in ntp-client.conf .
#
# NTPQV output version of "ntpq -c rv" 
# Version 4 is the most common and up to date version.
#
# If you are unsure, which to set, run this script and make sure that
# the JSON output variables match that in "ntpq -c rv".
#
################################################################
# Don't change anything unless you know what are you doing     #
################################################################
BIN_NTPQ='/usr/bin/env ntpq'
BIN_NTPD='/usr/bin/env ntpd'
BIN_GREP='/usr/bin/env grep'
BIN_SED="/usr/bin/env sed"
BIN_AWK='/usr/bin/env awk'
BIN_HEAD='/usr/bin/env head'
NTPQV=`$BIN_NTPD --version | $BIN_AWK -F'ntpd ' '{print $2}' | $BIN_HEAD -c 1`
# Load in custom file
CONFIG=$0".conf"
if [ -f $CONFIG ]; then
    . $CONFIG
fi
#error and errorString are hardcoded as if the above fails bad json will be generated
RAW=`$BIN_NTPQ -c rv | $BIN_GREP jitter | $BIN_SED 's/[[:alpha:]=,_]/ /g'`
if [ $NTPQV = "4" ]; then
    echo $RAW | $BIN_AWK -F ' ' '{print "{\"data\":{\"offset\":\""$2\
                        "\",\"frequency\":\""$3\
                        "\",\"sys_jitter\":\""$4\
                        "\",\"clk_jitter\":\""$5\
                        "\",\"clk_wander\":\""$6\
                        "\"},\"version\":\""'$NTPQV'"\",\"error\":\"0\",\"errorString\":\"\"}"
                        }'
    exit 0
elif [ $NTPQV != "4" ]; then
    echo $RAW | $BIN_AWK -F ' ' '{print "{\"data\":{\"offset\":\""$3\
                        "\",\"frequency\":\""$4\
                        "\",\"sys_jitter\":\""$5\
                        "\",\"clk_jitter\":\""$6\
                        "\",\"clk_wander\":\""$7\
                        "\"},\"version\":\""'$NTPQV'"\",\"error\":\"0\",\"errorString\":\"\"}"
                        }'
    exit 0
fi