#!/usr/bin/python
import json, subprocess
from subprocess import Popen, PIPE

input = Popen(['rec_control', 'get-all'], stdout=PIPE).communicate()[0]
data = []

for line in input.splitlines():
    item = line.split()
    data.append({'name': item[0].decode(), 'value': int(item[1].decode())})

print(json.dumps(data))
