#!/usr/bin/env bash

# - Copy this script to somewhere (like /opt/sdfsinfo.sh)
# - Make it executable (chmod +x /opt/sdfsinfo.sh)
# - Add the following line to your snmpd.conf file
#   extend sdfsinfo /opt/sdfsinfo.sh
# - Restart snmpd
#
# Note: Change the path accordingly, if you're not using "/opt/sdfsinfo.sh"

# You need the following tools to be in your PATH env, adjust accordingly
# - sdfscli, grep
PATH=$PATH

# SDFS info SNMP extend script
# datapoint -> info (type, descr):
# 00 -> files (int)
# 01 -> volume capacity (float, GB)
# 02 -> volume logical size (float, GB)
# 03 -> volume max load (float, %)
# 04 -> volume duplicate data (float, GB)
# 05 -> unique blocks stored (float, GB)
# 06 -> unique blocks stored after compression (float, GB)
# 07 -> cluster block copies (int)
# 08 -> volume dedup rate (float, %)
# 09 -> volume savings (float, %)
# 10 -> compression rate (float, %)

sdfscli --volume-info | grep -o -E "(([0-9]+)\.?([0-9]+)?)"
