#!/usr/bin/env bash

# - Copy this script to somewhere (like /opt/squid.sh)
# - Make it executable (chmod +x /opt/squid.sh)
# - Add the following line to your snmpd.conf file
#   extend squid /opt/squid.sh
# - Restart snmpd
#
# Note: Change the path accordingly, if you're not using "/opt/squid.sh"

# You need the following tools to be in your PATH env, adjust accordingly
# - snmpwalk
PATH=$PATH

# To get this working smoothly and securely, you can add the items below to your squid.conf.
# acl snmppublic snmp_community public
# snmp_port 3401
# snmp_access allow snmppublic localhost
# snmp_access deny all

# set this as being equal to the value of 'acl snmppublic snmp_community' in squid.conf
community='public'

# set this as being equal to the value of 'snmp_port' in squid.conf
port='3401'

##
## Nothing Should Need Changed Below Here
##

# cacheMemMaxSize Integer32
# cacheSwapMaxSize Integer32
# cacheSwapHighWM Integer32
# cacheSwapLowWM Integer32
snmpwalk -O qv -c $community -v 2c localhost:$port 1.3.6.1.4.1.3495.1.2.5

# cacheSysPageFaults Counter32
# cacheSysNumReads Counter32
# cacheMemUsage Integer32
# cacheCpuTime Integer32
# cacheCpuUsage Integer32
# cacheMaxResSize Integer32
# cacheNumObjCount Gauge32
# cacheCurrentLRUExpiration Timeticks
# Storage LRU Expiration Age
# cacheCurrentUnlinkRequests Gauge32
# cacheCurrentUnusedFDescrCnt Gauge32
# cacheCurrentResFileDescrCnt Gauge32
# cacheCurrentFileDescrCnt Gauge32
# cacheCurrentFileDescrMax Gauge32
snmpwalk -O qv -c $community -v 2c localhost:$port 1.3.6.1.4.1.3495.1.3.1

# cacheProtoClientHttpRequests Counter32
# cacheHttpHits Counter32
# cacheHttpErrors Counter32
# cacheHttpInKb Counter32
# cacheHttpOutKb Counter32
# cacheIcpPktsSent Counter32
# cacheIcpPktsRecv Counter32
# cacheIcpKbSent Counter32
# cacheIcpKbRecv Counter32
# cacheServerRequests Integer32
# cacheServerErrors Integer32
# cacheServerInKb Counter32
# cacheServerOutKb Counter32
# cacheCurrentSwapSize Gauge32
# cacheClients Gauge32 
snmpwalk -O qv -c $community -v 2c localhost:$port 1.3.6.1.4.1.3495.1.3.2.1

# cacheRequestHitRatio.1 Integer32
# cacheRequestHitRatio.5 Integer32
# cacheRequestHitRatio.60 Integer32
snmpwalk -O qv -c $community -v 2c localhost:$port 1.3.6.1.4.1.3495.1.3.2.2.1.9

# cacheRequestByteRatio.1 Integer32
# cacheRequestByteRatio.5 Integer32
# cacheRequestByteRatio.60 Integer32
snmpwalk -O qv -c $community -v 2c localhost:$port 1.3.6.1.4.1.3495.1.3.2.2.1.10
