#!/bin/sh

cat <<-EOM
#
## To get squid to work with librenms, add this to snmpd.conf.
   proxy -v 2c -c <your snmp_community> localhost:3401 .1.3.6.1.4.1.3495.1

## and add the items below to your squid.conf.

   acl snmppublic snmp_community <your snmp_community>
   snmp_port 3401
   snmp_access allow snmppublic localhost
   snmp_access deny all

EOM
