#!/usr/bin/env bash

# - Copy this script to somewhere (like /opt/unbound.sh)
# - Make it executable (chmod +x /opt/unbound.sh)
# - Add the following line to your snmpd.conf file
#   extend unbound /opt/unbound.sh
# - Restart snmpd
#
# Note: Change the path accordingly, if you're not using "/opt/unbound.sh"

# You need the following tools to be in your PATH env, adjust accordingly
# - unbound-control
PATH=$PATH

unbound-control stats
