#!/usr/bin/env sh
################################################################
# copy this script to /etc/snmp/ and make it executable:       #
# chmod +x /etc/snmp/unbound                                   #
# ------------------------------------------------------------ #
# edit your snmpd.conf and include:                            #
# extend unbound /etc/snmp/unbound                             #
# ------------------------------------------------------------ #
# restart snmpd and activate the app for desired host          #
# ------------------------------------------------------------ #
# please make sure you have the path/binaries below            #
################################################################
unbountctl='/usr/bin/env unbound-control'

##
## You should not need to change anything below.
##

$unbountctl stats
