#!/bin/sh

# Add this to snmpd.conf as below.
# extend unbound /root/snmp-extends/unbound

# Set the path to unbound-control.
unbountctl=`which unbound-control`

##
## You should not need to change anything below.
##

$unbountctl stats
