#!/usr/bin/php
<?php
$m = new Memcached();
$m->addServer('localhost', 11211);
$stats = $m->getStats();

if(is_array($stats))
{
  echo("<<<app-memcached>>>\n");
  echo(json_encode($m->getStats()));
  echo("\n");
}
