#!/usr/bin/env bash
################################################################
# copy this script to /etc/snmp/ and make it executable:       #
# chmod +x /etc/snmp/nfsstats                                  #
# ------------------------------------------------------------ #
# edit your snmpd.conf and include:                            #
# extend nfsstats /etc/snmp/nfsstats                           #
#--------------------------------------------------------------#
# restart snmpd and activate the app for desired host          #
#--------------------------------------------------------------#
# please make sure you have the path/binaries below            #
################################################################
CFG_NFSVER='3'
BIN_NFSSTAT='/usr/bin/env nfsstat'
BIN_TR='/usr/bin/env tr'
BIN_CUT='/usr/bin/env cut'
BIN_GREP='/usr/bin/env grep'
BIN_PASTE='/usr/bin/env paste'
BIN_RM='/usr/bin/env rm'
BIN_MV='/usr/bin/env mv'
LOG_OLD='/tmp/nfsstats_old'
LOG_NEW='/tmp/nfsstats_new'

$BIN_NFSSTAT -$CFG_NFSVER -n -l | $BIN_TR -s " " | $BIN_CUT -d ' ' -f 5 | $BIN_GREP -v '^$' > $LOG_NEW 2>&1

$BIN_PASTE $LOG_NEW $LOG_OLD | while read a b ; do
  echo $(($a - $b))  
done

$BIN_RM $LOG_OLD 2>&1
$BIN_MV $LOG_NEW $LOG_OLD 2>&1
