#!/usr/bin/python
import json, subprocess

input = subprocess.check_output(['rec_control', 'get-all'])
data = []

for line in input.splitlines():
    item = line.split()
    data.append({'name': item[0].decode(), 'value': int(item[1].decode())})

print('<<<powerdns-recursor>>>')
print(json.dumps(data))
